server:
  servlet:
    context-path: /thrifty
    session:
      timeout: 30m
      cookie:
        path: /
        http-only: true

spring:
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
---

debug: false
spring:
  profiles: dev
  jpa:
    show-sql: false
    hibernate.ddl-auto: create-drop
    properties.javax.persistence:
      schema-generation:
        drop-source: script
        drop-script-source: drop-tables.sql
      sql-load-script-source: test-data.sql
---

spring:
  profiles: prod
---
